name = "PhyLiNC"
uuid = "cc80c543-84d2-42fd-beda-26c7d0f745cc"
authors = ["Cecile Ane <cecileane@users.noreply.github.com>", "Cora Allen-Savietta <coraallensavietta@users.noreply.github.com>", "and contributors"]
version = "0.1.0-DEV"

[compat]
julia = "1.2"
